### PR TITLE
12371 reorganize tests

### PR DESCRIPTION
**Pull request by amullarney**
A shared classes test which covers Package References and inst_ref/set parameters on Port messages, for both Verifier and (currently) Ciera, replaces an older Package Reference test named for Verifier only.

### CODE REVIEW

**Comment by cortlandstarrett** [comment]
Alasdar, I think I see a .gitignore and a .project file at the top level of the repository.  Did you mean to commit these?
I am mostly concerned about the .project file.  I am not sure it makes sense to nest all of these projects inside a parent project.  Maybe it does.

**Comment by amullarney** [comment]
Both top-level .gitignore and .project are intentional - with John's advice.  
But if you know better...And we do have trouble with egit trying to put projects in lower level folders - we move the stuff into the git tree manually.Advice welcome.

    On Thursday, February 17, 2022, 08:59:49 AM PST, Cortland Starrett ***@***.***> wrote:  
 
 


Alasdar, I think I see a .gitignore and a .project file at the top level of the repository. Did you mean to commit these?
I am mostly concerned about the .project file. I am not sure it makes sense to nest all of these projects inside a parent project. Maybe it does.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cortlandstarrett** [comment]
Hmm, I have never had that problem.  And egit does provide that second "path within project" box under the selected repository and above the project when 'Sharing' a project into the repo.

I would like to merge the PR but omitting these 2 files.  I am comfortable changing a single model without deep review, but I prefer not to change the repository in a way that affects all projects.

I am happy to help with the troubles experienced around this if you can share more about what gets in your way.

**Comment by cortlandstarrett** [comment]
Screen Shot 2022-02-17 at 12 11 58 PM

**Comment by amullarney** [comment]
When I try to specify a path I get an error that there is a .project at the highest level.If you want me to resubmit with those files removed I'm fine with that. I will just make sure the .gitignore is good for my project.

    On Thursday, February 17, 2022, 09:14:30 AM PST, Cortland Starrett ***@***.***> wrote:  
 
 




—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cortlandstarrett** [comment]
Yes.  Perfect.  I will merge with these 2 omitted.

**Comment by amullarney** [comment]
Files removed and pushed.

    On Thursday, February 17, 2022, 09:21:15 AM PST, Cortland Starrett ***@***.***> wrote:  
 
 


Yes. Perfect. I will merge with these 2 omitted.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cortlandstarrett** [comment]
.project file is still present.

**Comment by amullarney** [comment]
I'm kinda hosed - I deleted .project locally and pushed; I don't understand why it still shows in the PR.But, now I cannot open the models repo in BP Project Explorer - error - missing .project file.. and with it my model!

    On Thursday, February 17, 2022, 10:32:43 AM PST, Cortland Starrett ***@***.***> wrote:  
 
 


.project file is still present.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by amullarney** [comment]
Superceded by #337

**Pull request closed without merging**
