### PR TITLE
Fixes for MASL models found via new editor

### PR DESCRIPTION
**Pull request by JanKoehnlein**

### CODE REVIEW

**Comment by JanKoehnlein** [comment]
I've added some declarations for missing elements and removed duplicate definitions from the MASL example models.
The errors and duplicates were detected using the new editor. With these patches, the new editor does not produce any more errors, just a couple of warnings for pending declarations (without an appropriate definition).

**Comment by leviathan747** [comment]
Hey Jan, I just reviewed your PR and I have two comments.

First, as we discussed before, there are some deprecated types polluting this model data. I have spoken with our customer and they would like us to remove them. "Text" and "Integer" are the only ones that appear in these models. Each instance of "Text" in the model data should be replaced with "string" and instances of "Integer" should be replaced with "integer". I did a quick search, and this is the list of occurrences I have found:

```bash
01:26 PM-~/git/xtuml/models/masl$ grep -nr Text .
./SAC/SAC_OOA/SCON_get_groups.tr:13:the_group_name : Text;
./SAC/SAC_OOA/SCON_get_groups.tr:14:operation_name : Text;
./SAC/SAC_OOA/SCON_get_groups.tr:15:operation_names : sequence of Text;
./SAC/SAC_OOA/SCON_get_groups.tr:16:empty_operation_names : sequence of Text;
./SAC/SAC_OOA/soa_subscribe_2.scn:9:soa_messages : sequence of Text;
./SAC/SAC_OOA/soa_subscribe_2.scn:10:empty_soa_messages : sequence of Text;
./SAC/SAC_OOA/test_SAC_1.ext:9:the_groups : sequence of Text;
./SAC/SAC_OOA/test_SAC_1.ext:10:empty_groups : sequence of Text;
./SAC/SAC_OOA/user_logon.svc:25:message : Text;
01:26 PM-~/git/xtuml/models/masl$ grep -nr Integer .
./PSC/PSC_OOA/PSC.int:67:  type Timer_ID is Integer;
./PSC/PSC_OOA/PSC.mod:68:  type Timer_ID is Integer;
```

Second, I see that a lot of files have been deleted. I am wondering if you are not clear on why they are there and their purpose for interfacing the domains. Do you need clarification on that?

Thank you, this is great work.
Levi

**Comment by JanKoehnlein** [comment]
1) I replaced the deprecated types as you advised.
2) The deleted files contain definitions (not declarations) of services/object/functions etc. that are also present in other files in the same project. They were easy to spot as I added a duplicate name detection for definitions. I suppose they come from some initial automatic transformation and have not been cleaned up after they were copied to a better location.

**Comment by leviathan747** [comment]
Actually, these duplicates are intentional. Your confusion is understandable since this was not clearly documented anywhere. The .tr files in the project directory alongside the .prj files are _overriding_ the .tr files of the same name in the corresponding domain directory alongside the .mod file. The reason for this pattern is that each domain is an independently compilable piece. The terminators serve as interfaces to the outside world, so the .tr files in a domain directory typically only contain the "null" statement and stub out the functionality. Then when an engineer comes along and wants to build a multi-domain application, he writes .tr files in the project directory to "wire" all the domains together through the terminators.

**Comment by JanKoehnlein** [comment]
So why don't you just use Terminator Service/Function *declarations* in the domain directory and definitions in the project directory? What sense do the null stubs make?

**Comment by leviathan747** [comment]
The idea is that each domain is a distinct set of functionality. It can be compiled and run apart from a project file. In that case, the definitions would never be overridden and would simply do nothing.

**Comment by JanKoehnlein** [comment]
What a messy language: Things can be *declared* and *defined* twice :-( 
Is there a way to distinguish between the external declarations / definitions and the internal ones? Maybe a directory naming convention or the like?

**Comment by leviathan747** [comment]
The source directories are separate. To take GPS for example:

There is one directory for the project definition -- GPSWatch. This includes the .prj file and a handful of .tr files that are going to override terminator services/functions in the domains.

There are four separate directories for each of the four domains -- Tracking, HeartRateMonitor, UI, and Location. Each has its .mod file, a collection of other activity files, and any .int files that contain dependencies from other domains.

The customer compiles each of these five directories independently and the duplications are dealt with at "link time". I put quotes because our customer is actually generating C++ from this language, so they have some mechanism or method to discard the generated stubs from the domains in favor of the real definitions in the project. Projects and domains are not ever parsed/compiled at the same time by the customer. Each domain and each project should be seen as a separate compilation unit.

**Pull request merged**
